[package]
name = "openchat-account-core"
version.workspace = true
edition.workspace = true

[lib]
name = "openchat_account_core"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
argon2 = "0.5"
base64 = "0.22"
chacha20poly1305 = "0.10"
hmac = "0.12"
openchat-core = { path = "../openchat-core" }
openchat-infra = { path = "../infra" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
